Feature/playback get imu sample
etiennedub/pyk4a pull request #150
Opened 2021-10-08 11:12 UTC by annStein

For playback.py I added the method to get the next imu sample.

2021-12-14 16:33 UTC, lpasselin commented
Sorry, I did not notice this PR until today! Thanks for the contribution, this looks well done.

@shagren it seems perfect but could you test?

2021-12-15 09:07 UTC, shagren commented on pyk4a/playback.py
> +    def get_next_imu_sample(self) -> Optional["ImuSample"]:
Please add
```python
from .pyk4a import ImuSample
```
before
```python
from .results import Result, StreamResult
```

2021-12-15 09:10 UTC, shagren requested changes
Great, just two small changes for better quality

2021-12-15 09:10 UTC, shagren commented on pyk4a/playback.py
> +    def get_next_imu_sample(self) -> Optional["ImuSample"]:
Please add
```python
from .pyk4a import ImuSample
```
before
```python
from .results import Result, StreamResult
```

2021-12-15 09:10 UTC, shagren commented on pyk4a/pyk4a.cpp
> +                         imu_sample.gyro_timestamp_usec);
```suggestion
                       imu_sample.acc_sample.xyz.x, imu_sample.acc_sample.xyz.y, imu_sample.acc_sample.xyz.z,
                       "acc_timestamp", imu_sample.acc_timestamp_usec, "gyro_sample", imu_sample.gyro_sample.xyz.x,
                       imu_sample.gyro_sample.xyz.y, imu_sample.gyro_sample.xyz.z, "gyro_timestamp",
                       imu_sample.gyro_timestamp_usec);
```

Just remove 2 spaces on these lines

2022-01-17 10:35 UTC, annStein commented
Sorry, now I didn't see your comments for a long time. Hopefully this can be closed soon now. :)

2022-01-17 11:07 UTC, shagren approved these changes
LGTM

2022-01-18 19:49 UTC, merged